apiVersion: v1
kind: Service
metadata:
  name: cluterip-postgresql
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
    - port: 5432
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 5432
