apiVersion: v1
kind: Service
metadata:
  name: web-entry
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8000
