apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: gilzafire/django-site:v8
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        env:
        - name: DB_NAME
          value: "AfterDB"
        - name: DB_USER
          value: "django"
        - name: DB_PASSWORD
          value: "django"
        - name: DB_HOST
          value: "cluterip-postgresql"
        - name: DB_PORT
          value: "5432"
        ports:
        - containerPort: 8000
